playerandai1:
	clang++ -std=c++11 -o playerandai1 main.cpp `pkg-config --cflags --libs ncurses` `pkg-config --cflags --libs openssl` -DLINUX -DINITNCURSESNOW -DINITNCURSESNOW2 -DINITOPENSSL
	
clean:
	rm -f playerandai1

